/**
 * Mermaid diagram exporters for flow map pipelines and WS round-trips.
 */

function sanitizeId(str) {
    return String(str || 'node').replace(/[^a-zA-Z0-9_]/g, '_');
}

function formatNodeLabel(text, sub) {
    const main = String(text).replace(/"/g, '#quot;');
    if (sub) {
        const subEsc = String(sub).replace(/"/g, '#quot;');
        return `"${main}<br/><small>${subEsc}</small>"`;
    }
    return `"${main}"`;
}

/**
 * Sequence diagram for a WS request/response pipeline.
 * @param {object} pipeline from resolvePipeline()
 */
function pipelineToSequenceMermaid(pipeline, allClientInbound) {
    const req = pipeline.requestType || pipeline.key;
    const lines = ['sequenceDiagram'];

    lines.push('    participant UI as Client UI');
    lines.push('    participant WS as websocket.js');
    lines.push('    participant SRV as Server Handler');
    lines.push('    participant IMPL as Handler Impl');

    const callers = pipeline.link?.client?.callers || [];
    const uniqueCallers = dedupeCallers(callers);

    if (uniqueCallers.length) {
        for (const c of uniqueCallers.slice(0, 5)) {
            lines.push(`    UI->>WS: ${c.callerFn}()`);
        }
    } else {
        lines.push('    UI->>WS: (caller)');
    }

    lines.push(`    WS->>SRV: ${req}`);

    const reg = pipeline.link?.server?.registration;
    if (reg) {
        lines.push(`    Note over SRV: ${reg.file}:${reg.line}`);
        if (reg.handlerFn && reg.handlerFn !== '(legacy switch)') {
            lines.push(`    SRV->>IMPL: ${reg.handlerFn}()`);
        }
    }

    const responseTypes = pipeline.responseTypes?.length
        ? pipeline.responseTypes
        : (pipeline.link?.responseTypes || []);

    const inboundPool = allClientInbound || pipeline.link?.client?.inbounds || [];

    for (const rt of responseTypes) {
        const inbound = inboundPool.find((i) => i.type === rt);
        const handlerNote = inbound
            ? `${inbound.file} (${inbound.handlerRef || inbound.id})`
            : 'client handler';
        lines.push(`    IMPL-->>WS: ${rt}`);
        lines.push(`    WS-->>UI: ${handlerNote}`);
    }

    return lines.join('\n');
}

function dedupeCallers(callers) {
    const seen = new Set();
    return callers.filter((c) => {
        const k = `${c.file}:${c.callerFn}`;
        if (seen.has(k)) return false;
        seen.add(k);
        return true;
    });
}

/**
 * Flowchart for server-side call graph within an impl file.
 */
function callGraphToFlowchartMermaid(callGraph, title) {
    if (!callGraph || !callGraph.edges.length) {
        return `flowchart TD\n    empty["${title || callGraph?.file || 'No calls'} — no internal edges detected"]`;
    }

    const lines = ['flowchart TD'];
    if (title) {
        lines.push(`    subgraph ${sanitizeId(title)} ["${title}"]`);
    }

    const nodeIds = new Map();
    for (const fn of callGraph.functions) {
        const id = sanitizeId(fn);
        nodeIds.set(fn, id);
        const label = fn.replace(/"/g, '#quot;');
        lines.push(`        ${id}["${label}"]`);
    }

    for (const edge of callGraph.edges) {
        const from = nodeIds.get(edge.from) || sanitizeId(edge.from);
        const to = nodeIds.get(edge.to) || sanitizeId(edge.to);
        lines.push(`        ${from} --> ${to}`);
    }

    if (title) lines.push('    end');
    return lines.join('\n');
}

/**
 * High-level WS packet map (client ↔ server) for an owner/domain.
 */
function ownerToGraphMermaid(owner, links) {
    const lines = ['flowchart LR'];
    const ownerLinks = links.filter((l) => l.owner === owner && l.requestType);

    lines.push(`    subgraph client ["Client"]`);
    lines.push(`        wsclient["websocket.js"]`);
    lines.push('    end');

    lines.push(`    subgraph server ["Server — ${owner}"]`);
    for (const link of ownerLinks.slice(0, 20)) {
        const id = sanitizeId(link.requestType);
        lines.push(`        ${id}${formatNodeLabel(link.requestType, link.server?.registration?.handlerFn)}`);
        lines.push(`        wsclient --> ${id}`);
        for (const rt of (link.responseTypes || []).slice(0, 3)) {
            const rid = sanitizeId(rt);
            lines.push(`        ${id} --> ${rid}${formatNodeLabel(rt)}`);
            lines.push(`        ${rid} --> wsclient`);
        }
    }
    lines.push('    end');

    return lines.join('\n');
}

/**
 * Full markdown document for a pipeline export.
 */
function pipelineToMarkdown(pipeline, callGraph, options = {}) {
    const title = pipeline.label || pipeline.requestType || pipeline.key;
    const allInbound = options.allClientInbound || pipeline.link?.client?.inbounds || [];
    const seq = pipelineToSequenceMermaid(pipeline, allInbound);
    const sections = [
        `# Flow Map: ${title}`,
        '',
        `> Auto-generated by \`node scripts/tools/flow-map.js pipeline ${pipeline.key || pipeline.requestType}\``,
        `> Scanned: static analysis (regex/heuristic) — not runtime traced.`,
        '',
        '## WebSocket Round-Trip',
        '',
        '```mermaid',
        seq,
        '```',
        ''
    ];

    if (pipeline.link?.server?.registration) {
        const reg = pipeline.link.server.registration;
        sections.push('## Server Handler', '');
        sections.push(`| Field | Value |`);
        sections.push(`| --- | --- |`);
        sections.push(`| Packet | \`${reg.type}\` |`);
        sections.push(`| Owner | \`${reg.owner}\` |`);
        sections.push(`| File | \`${reg.file}:${reg.line}\` |`);
        if (reg.handlerFn) sections.push(`| Function | \`${reg.handlerFn}\` |`);
        if (pipeline.link.server.implFile) {
            sections.push(`| Impl | \`${pipeline.link.server.implFile}\` |`);
        }
        sections.push('');
    }

    const callers = pipeline.link?.client?.callers || [];
    if (callers.length) {
        sections.push('## Client Callers', '');
        sections.push('| File | Function | Line |');
        sections.push('| --- | --- | --- |');
        for (const c of dedupeCallers(callers).slice(0, 15)) {
            sections.push(`| \`${c.file}\` | \`${c.callerFn}\` | ${c.line} |`);
        }
        sections.push('');
    }

    const responseFilter = pipeline.responseTypes?.length ? new Set(pipeline.responseTypes) : null;
    const inbounds = allInbound.filter((i) =>
        !responseFilter || responseFilter.has(i.type)
    );
    if (inbounds.length) {
        sections.push('## Client Inbound Handlers', '');
        sections.push('| Type | File | Handler | Phase |');
        sections.push('| --- | --- | --- | --- |');
        for (const i of inbounds) {
            sections.push(`| \`${i.type}\` | \`${i.file}\` | \`${i.handlerRef || i.id}\` | ${i.phase} |`);
        }
        sections.push('');
    }

    if (callGraph && callGraph.edges.length) {
        sections.push('## Server Impl Call Graph', '');
        sections.push('```mermaid');
        sections.push(callGraphToFlowchartMermaid(callGraph, pathBasename(callGraph.file)));
        sections.push('```', '');
    }

    if (options.limitations !== false) {
        sections.push('## Limitations', '');
        sections.push('- Static scan only; dynamic `sendMessage(type)` and runtime-registered handlers may be missed.');
        sections.push('- Cross-file JavaScript calls are not fully resolved.');
        sections.push('- Re-run `pnpm flow-map pipeline <name>` after handler changes.');
        sections.push('');
    }

    return sections.join('\n');
}

function pathBasename(file) {
    return String(file || '').split('/').pop();
}

module.exports = {
    pipelineToSequenceMermaid,
    callGraphToFlowchartMermaid,
    ownerToGraphMermaid,
    pipelineToMarkdown,
    sanitizeId
};
