import sys
import re

def main():
    with open('modules/mcpAgentFacade.js', 'r') as f:
        content = f.read()

    # Add tool definitions
    new_tools = """
    {
        name: 'run_client_js',
        description: 'Execute raw JavaScript in the bound Dreamscape client context.',
        scope: 'generation',
        inputSchema: {
            type: 'object',
            additionalProperties: false,
            properties: {
                script: { type: 'string', description: 'Raw JS expression or script string to execute' }
            },
            required: ['script']
        }
    },
    {
        name: 'inspect_elements',
        description: 'Inspect elements in the bound Dreamscape client matching CSS selectors.',
        scope: 'generation',
        inputSchema: {
            type: 'object',
            additionalProperties: false,
            properties: {
                selectors: { type: 'array', items: { type: 'string' }, description: 'CSS selectors to match' },
                html: { type: 'boolean', description: 'Include outerHTML in response (default true)' },
                style: { type: 'boolean', description: 'Include getComputedStyle in response (default true)' },
                styleAllowlist: { type: 'array', items: { type: 'string' }, description: 'Optional list of CSS properties to include from computed style' }
            },
            required: ['selectors']
        }
    },
    {
        name: 'apply_preset_to_studio',"""

    content = content.replace("    {\n        name: 'apply_preset_to_studio',", new_tools)


    # Add TOOL_RATE_GROUPS entries
    rate_groups = """
    run_client_js: 'studio',
    inspect_elements: 'studio',
    apply_preset_to_studio: 'studio',"""
    content = content.replace("    apply_preset_to_studio: 'studio',", rate_groups)

    # Add implementations in callTool logic (around apply_studio_changes)
    impl = """    if (name === 'apply_studio_changes') {
        const bind = autoBindIfNeeded(globalResources, req);
        if (!getBoundRecord(globalResources, bind.bindKey)) {
            return mcpBindChoiceResult(bind);
        }
        const blocked = await guardStudioAutoGenerateDynagen(globalResources, bind.bindKey, input);
        if (blocked) {
            return mcpTextResult(blocked, true);
        }
        const data = await applyStudioChanges(globalResources, { ...input, bindKey: bind.bindKey });
        rememberStudioCheckpointFromState(bind.bindKey, data);
        let responseNext;
        if (data && data.vSliderRejected > 0) {
            responseNext = 'vSlider catalog did not hydrate. Each widget needs kind (slider/xypad/star/dropdown), axes with stops[{at,text}] (2+ per axis), and target expander prefix. Do not substitute static expanders — retry apply_studio_changes with a corrected vSlider array.';
        } else if (data && data.generateStarted) {
            responseNext = 'apply does not return pixels. Call get_generated_image (that filename or latest) with dest_path, then render_file /home/workdir/artifacts/… after curling url if missing. Do not reprint with Grok Imagine.';
        }
        return mcpTextResult({
            success: true,
            autoBound: !!bind.auto,
            ...data,
            ...(responseNext ? { next: responseNext } : {})
        });
    }

    if (name === 'run_client_js' || name === 'inspect_elements') {
        const bind = autoBindIfNeeded(globalResources, req);
        if (!getBoundRecord(globalResources, bind.bindKey)) {
            return mcpBindChoiceResult(bind);
        }
        const data = await sendBoundCommand(globalResources, name, input, 15000, bind.bindKey);
        return mcpTextResult({
            success: true,
            autoBound: !!bind.auto,
            ...data
        });
    }"""

    # We replace from "if (name === 'apply_studio_changes') {" up to its closing brace (which is right before "if (name === 'sync_ship_cake') {" with Cake Pantry)

    # Let's use a regex or string slice to be safer
    search_str = "    if (name === 'apply_studio_changes') {\n        const bind = autoBindIfNeeded(globalResources, req);\n        if (!getBoundRecord(globalResources, bind.bindKey)) {\n            return mcpBindChoiceResult(bind);\n        }\n        const blocked = await guardStudioAutoGenerateDynagen(globalResources, bind.bindKey, input);\n        if (blocked) {\n            return mcpTextResult(blocked, true);\n        }\n        const data = await applyStudioChanges(globalResources, { ...input, bindKey: bind.bindKey });\n        rememberStudioCheckpointFromState(bind.bindKey, data);\n        let responseNext;\n        if (data && data.vSliderRejected > 0) {\n            responseNext = 'vSlider catalog did not hydrate. Each widget needs kind (slider/xypad/star/dropdown), axes with stops[{at,text}] (2+ per axis), and target expander prefix. Do not substitute static expanders — retry apply_studio_changes with a corrected vSlider array.';\n        } else if (data && data.generateStarted) {\n            responseNext = 'apply does not return pixels. Call get_generated_image (that filename or latest) with dest_path, then render_file /home/workdir/artifacts/… after curling url if missing. Do not reprint with Grok Imagine.';\n        }\n        return mcpTextResult({\n            success: true,\n            autoBound: !!bind.auto,\n            ...data,\n            ...(responseNext ? { next: responseNext } : {})\n        });\n    }"

    if search_str in content:
        content = content.replace(search_str, impl)
    else:
        print("Warning: could not find apply_studio_changes block to patch.")

    with open('modules/mcpAgentFacade.js', 'w') as f:
        f.write(content)

if __name__ == "__main__":
    main()
